In [13]:
from random import *
import numpy as np

num = int(input())  #get size from user
k=0
l=0
arr = np.random.random((num,num))  # make num X num random array
arr2 = np.zeros((int(num/2),int(num/2))) # make half size of precious random array and initialize the element zero
for i in range(1,num,2): 
  for j in range(1,num,2): # to find max value in 2X2 array, use double for loop and make steps 2
    max = 0
    for k in range(0,2):
      for p in range(0,2):  # find max value in 2x2 array
        if arr[i-k][j-p]>max:
          max = arr[i-k][j-p]
    arr2[int(i/2)][int(j/2)]=max  #and assign the max value to proper position of zero array
print(arr)
print(arr2)


8
[[0.27737439 0.27111636 0.55256784 0.03123764 0.08903282 0.2492061
  0.48422666 0.12586598]
 [0.89345858 0.89278281 0.91076802 0.60999214 0.78076655 0.78360301
  0.02658402 0.38217945]
 [0.31080248 0.29656001 0.10094422 0.67587536 0.74599088 0.60738643
  0.79194919 0.27223085]
 [0.06289745 0.60090927 0.76576821 0.10032027 0.60246777 0.32726774
  0.79934332 0.88967322]
 [0.66653111 0.75433477 0.41183213 0.70087412 0.56173744 0.4912609
  0.43822826 0.46029431]
 [0.0515564  0.33711286 0.16062685 0.70661055 0.55164049 0.75706079
  0.50321283 0.01798308]
 [0.99132753 0.70087954 0.56604949 0.23683143 0.41487692 0.80894321
  0.06035897 0.44491336]
 [0.94003038 0.84478484 0.22048488 0.0456004  0.40488532 0.157754
  0.1888768  0.87419512]]
[[0.89345858 0.91076802 0.78360301 0.48422666]
 [0.60090927 0.76576821 0.74599088 0.88967322]
 [0.75433477 0.70661055 0.75706079 0.50321283]
 [0.99132753 0.56604949 0.80894321 0.87419512]]
